#version: "3.9"

services:
  app: # Contenedor de la aplicación
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./src:/app/src
      - ./src/db:/app/db  # Volumen persistente para la base de datos SQLite
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    networks:
      - app-network
    #platform: linux/arm64/v8

  db: # Contenedor para almacenar la base de datos SQLite
    image: nouchka/sqlite3  # Imagen base de SQLite
    volumes:
      - ./src/db:/app/db  # Volumen persistente para la base de datos SQLite
    networks:
      - app-network
    environment:
      - SQLITE_DATABASE=/app/db/database.db  # Ruta al archivo de base de datos dentro del contenedor
    #platform: linux/arm64/v8

  tests: # Contenedor para ejecutar las pruebas
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest --cov=src
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./tests:/app/tests
    depends_on:
      - app
    networks:
      - app-network
    #platform: linux/arm64/v8

networks: # Red compartida por los servicios
  app-network:
    driver: bridge

