version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

  db:
    image: sqlite:latest
    volumes:
      - ./src/db/database.db:/data/database.db
    networks:
      - app-network

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest --cov=src
    volumes:
      - ./src:/app/src
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

